// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWuJ3L4aKTy6MlK_zkq_KXgeBRt875N2Q',
    appId: '1:538577518009:web:d50f1554c325cb0adf0a68',
    messagingSenderId: '538577518009',
    projectId: 'mifei-589d5',
    authDomain: 'mifei-589d5.firebaseapp.com',
    storageBucket: 'mifei-589d5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdIaIZIQJR-88kGq0ozFq8pAAYZ-KO8o4',
    appId: '1:538577518009:android:ebef0f6696432ad0df0a68',
    messagingSenderId: '538577518009',
    projectId: 'mifei-589d5',
    storageBucket: 'mifei-589d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCENaJoPJDQtkfUKxgNtfJZmKi0k2iA5wI',
    appId: '1:538577518009:ios:ebbe8be82a8cff7bdf0a68',
    messagingSenderId: '538577518009',
    projectId: 'mifei-589d5',
    storageBucket: 'mifei-589d5.appspot.com',
    iosClientId: '538577518009-4ihq4dpl3ft17djumos18a99jffmu6bq.apps.googleusercontent.com',
    iosBundleId: 'com.example.mifei',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCENaJoPJDQtkfUKxgNtfJZmKi0k2iA5wI',
    appId: '1:538577518009:ios:ebbe8be82a8cff7bdf0a68',
    messagingSenderId: '538577518009',
    projectId: 'mifei-589d5',
    storageBucket: 'mifei-589d5.appspot.com',
    iosClientId: '538577518009-4ihq4dpl3ft17djumos18a99jffmu6bq.apps.googleusercontent.com',
    iosBundleId: 'com.example.mifei',
  );
}
